[supervisord]
nodaemon=true

[program:apache2]
command=/usr/sbin/apache2ctl -D FOREGROUND
autostart=true
autorestart=true

[program:turnprocessor]
command=php /turn_processor.php
autostart=true
autorestart=true
environment=DB_HOST="%(ENV_MYSQLHOST)s",DB_NAME="%(ENV_MYSQLDATABASE)s",DB_USER="%(ENV_MYSQLUSER)s",DB_PASSWORD="%(ENV_MYSQLPASSWORD)s"